 title: <p align="center"> Merykokeb Belay </p>

#logo: "/images/picture.png?raw=true"

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/merykokeb-belay-bb228613b">LinkedIn</a> |
  <a href="https://github.com/mkkbelay">GitHub</a>
  </p>
  
  <p align="justify">
  I am pursing a MS degree in Data Science for Public Policy at the McCourt School of Public Policy, Georgetown University.
#   <br><br>
#   I am currently a Machine Learning Research Intern at Skim AI Technologies with a focus on NLP and Deep Learning research.
#   <br><br>
  </p>
  
  theme: jekyll-theme-minimal
