title: <p align="center"> Merykokeb Belay </p>
logo: "/images/profile_pic.png"
description:
  <p align="center">
  <a href="">Resume</a> |
  <a href="https://www.linkedin.com/in/merykokeb-belay-bb228613b">LinkedIn</a> |
  <a href="">GitHub</a>
  </p>
  <p align="justify">
  Hi! My name is Merykokeb Belay. I have a background in social science research and  recently completed a master’s degree in data science and public policy. I have experience assisting product and research teams with analytics tasks and enjoy using data to extract meaningful insights. 
  </p>
theme: jekyll-theme-minimal
github: 
  is_project_page: false

