title: <p align="center"> Merykokeb Belay </p>
#logo: <center><img src="images/profile_pic.png"/></center>
description:
  <p align="center">
  <a href="">Resume</a> |
  <a href="https://www.linkedin.com/in/merykokeb-belay-bb228613b">LinkedIn</a> |
  <a href="">GitHub</a>
  </p>
  <p align="justify">
  I am pursing a MS degree in Data Science and Public Policy at McCourt School of Public Policy, Georgetown University.
  # <br><br>
  # Lorum Ipsum.
  # <br><br>
  </p>
  
theme: jekyll-theme-minimal 
